POST https://newtrips-backend.onrender.com/subscriptions
Content-Type: application/json

{
    "name": "Eduardo Lima",
    "email": "pitfall_lima@hotmail.com",
    "plan": "Sky",
    "status": "Inativo",
    "address": "Rua Bonfim da Feira, 222 - Jardim São Paulo",
    "state": "São Paulo",
    "city": "São Paulo",
   "cep": "08430-770",
    "cpf": "869.782.800-70"
}

### 

GET https://newtrips-backend.onrender.com/subscriptions

### 

GET https://newtrips-backend.onrender.com/subscriptions?search=cancelado

###
GET https://newtrips-backend.onrender.com/subscriptions/00786d23-3bea-4af8-9820-48631325bf13

###
PUT https://newtrips-backend.onrender.com/subscriptions/10359648-baf6-40aa-9940-92517b3388f8
Content-Type: application/json

{
    "name": "Fernanda Cruz",
    "email": "fernanda_cruz@gmail.com",
    "plan": "Sky",
    "status": "cancelado",
    "address": "Rua Bonfim da Feira, 222 - Jardim São Paulo",
    "state": "São Paulo",
    "city": "São Paulo",
    "cep": "08430-770",
    "cpf": "869.782.800-70"
}

###

DELETE http://localhost:3333/subscriptions/5ad81cc3-e5f5-49bb-a31e-c7645173bfc3