POST https://newtrips-backend.onrender.com/subscriptions
Content-Type: application/json

{
    "id": 2353768,
    "name": "Fernanda Cruz",
    "email": "fernanda_cruz@gmail.com",
    "plan": "Explorer",
    "status": "Ativo",
    "address": "Rua Bonfim da Feira, 222 - Jardim São Paulo",
    "state": "São Paulo",
    "city": "São Paulo",
   "cep": "08430-770",
    "cpf": "869.782.800-70"
}

### 

GET https://newtrips-backend.onrender.com/subscriptions?search=ativo

###
PUT https://newtrips-backend.onrender.com/subscriptions/5ad81cc3-e5f5-49bb-a31e-c7645173bfc3
Content-Type: application/json

{
     "id": 2353768,
    "name": "Fernanda Cruz",
    "email": "fernanda_cruz@gmail.com",
    "plan": "Sky",
    "status": "Ativo",
    "address": "Rua Bonfim da Feira, 222 - Jardim São Paulo",
    "state": "São Paulo",
    "city": "São Paulo",
    "cep": "08430-770",
    "cpf": "869.782.800-70"
}

###

DELETE http://localhost:3333/subscriptions/5ad81cc3-e5f5-49bb-a31e-c7645173bfc3