POST https://newtrips-backend.onrender.com/videos
Content-Type: application/json

{
    "title": "Vídeo node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

### 

GET https://newtrips-backend.onrender.com/videos?search=0

###
PUT https://newtrips-backend.onrender.com/videos/8221bf9c-5528-4063-b6e9-7bb988425f0a
Content-Type: application/json

{
    "title": "Vídeo 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE https://newtrips-backend.onrender.com/videos/8221bf9c-5528-4063-b6e9-7bb988425f0a